## 0. Import Packages

In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
# conda install PyTorch -c PyTorch

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display, Math, Latex
torch.manual_seed(1)

## 1. Variables

In [4]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [8]:
print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


## 2. Weight and Bias

In [18]:
# Initialize weights with 0
W = torch.zeros(1, requires_grad = True) # trainable
b = torch.zeros(1, requires_grad=True)

print(W) 
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


- y = 0×x+0

## 3. Hypothesis
- H(x)=Wx+b

In [19]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


## 4. Cost Function

In [20]:
display(Math(r'\frac{1}{n} \sum_{i=1}^{n} \left[y^{(i)} - H(x^{(i)})\right]^2'))

<IPython.core.display.Math object>

In [21]:
cost = torch.mean((hypothesis - y_train) ** 2) 
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


## 5. Gradient Descent

In [22]:
optimizer = optim.SGD([W, b], lr = 0.01)

# initialize gradient with 0
optimizer.zero_grad() 

# diff cost function
cost.backward() 

# update W and b
optimizer.step() 

## 6. Linear Regression

In [23]:
# data
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# initialize W and b
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs + 1):

    # Hypothesis
    hypothesis = x_train * W + b

    # cost
    cost = torch.mean((hypothesis - y_train) ** 2)

    # update
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # print
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/2000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/2000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/2000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/2000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/2000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/2000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/2000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/2000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/2000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/2000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b: 0.008 Cost: 0.000008

## 6+. Linear regression with nn.Module

In [27]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

model = nn.Linear(1,1) # initialize (input_dim=1, output_dim=1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [29]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x)
    prediction = model(x_train)

    # cost
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # initialize gradient with 0
    optimizer.zero_grad()
    
    # calculate gradient
    cost.backward() 
    # update
    optimizer.step()

    if epoch % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [32]:
new_var =  torch.FloatTensor([[4.0]]) 
pred_y = model(new_var) # forward 

print("prediction :", pred_y) 
print(list(model.parameters()))

prediction : tensor([[7.9989]], grad_fn=<AddmmBackward>)
[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


## 7. AutoGrad

In [24]:
w = torch.tensor(2.0, requires_grad=True)

y = w**2
z = 2*y + 5

z.backward()
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0


## 8. Multivariable Linear regression

In [26]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

# initialize W and b
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 
    # b : broadcasting
    hypothesis = x_train.matmul(W) + b

    # cost
    cost = torch.mean((hypothesis - y_train) ** 2)

    # update
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # print
    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605]) Cost: 9298.520508
Epoch    2/20 hypothesis: tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821]) Cost: 2915.712402
Epoch    3/20 hypothesis: tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097]) Cost: 915.040527
Epoch    4/20 hypothesis: tensor([137.7968, 165.6247, 163.1911, 177.7112, 126.3307]) Cost: 287.936005
Epoch    5/20 hypothesis: tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891]) Cost: 91.371010
Epoch    6/20 hypothesis: tensor([148.1035, 178.0144, 175.3980, 191.0042, 135.7812]) Cost: 29.758139
Epoch    7/20 hypothesis: tensor([150.1744, 180.5042, 177.8508, 193.6753, 137.6805]) Cost: 10.445305
Epoch    8/20 hypothesis: tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440]) Cost: 4.391228
Epoch    9/20 hypothesis: tensor([151.9824, 182.6789, 179.9928, 196.0079, 139.3396]) Cost: 2.493135
Epoch   10/20 hypo

## 8+. Multivariable Linear regression with nn.Module

In [33]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [34]:
model = nn.Linear(3,1)  # input_dim=3, output_dim=1
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [35]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x)
    prediction = model(x_train)
    # model(x_train) = model.forward(x_train)

    # cost
    cost = F.mse_loss(prediction, y_train) # pytorch mse

    # initialzie gradient with 0
    optimizer.zero_grad()
    # calculate gradient
    cost.backward()
    # update
    optimizer.step()

    if epoch % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 42134.707031
Epoch  100/2000 Cost: 5.960053
Epoch  200/2000 Cost: 5.654707
Epoch  300/2000 Cost: 5.365413
Epoch  400/2000 Cost: 5.091429
Epoch  500/2000 Cost: 4.831834
Epoch  600/2000 Cost: 4.585997
Epoch  700/2000 Cost: 4.353075
Epoch  800/2000 Cost: 4.132411
Epoch  900/2000 Cost: 3.923455
Epoch 1000/2000 Cost: 3.725502
Epoch 1100/2000 Cost: 3.537972
Epoch 1200/2000 Cost: 3.360326
Epoch 1300/2000 Cost: 3.192056
Epoch 1400/2000 Cost: 3.032674
Epoch 1500/2000 Cost: 2.881700
Epoch 1600/2000 Cost: 2.738672
Epoch 1700/2000 Cost: 2.603201
Epoch 1800/2000 Cost: 2.474846
Epoch 1900/2000 Cost: 2.353286
Epoch 2000/2000 Cost: 2.238110


In [36]:
new_var =  torch.FloatTensor([[73, 80, 75]])  # multi values
pred_y = model(new_var) 
print("prediction :", pred_y) 

prediction : tensor([[153.7184]], grad_fn=<AddmmBackward>)


In [37]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.8541, 0.8475, 0.3096]], requires_grad=True), Parameter containing:
tensor([0.3568], requires_grad=True)]


## 9. Class and Module - Linear Regression

In [38]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)  # input_dim=1, output_dim=1

    def forward(self, x):
        return self.linear(x)

In [42]:
model = LinearRegressionModel()
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [40]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [43]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x)
    prediction = model(x_train)

    # cost
    cost = F.mse_loss(prediction, y_train)

    # initialize gradient with 0
    optimizer.zero_grad()
    # calculate gradient
    cost.backward() # backward
    # update
    optimizer.step()

    if epoch % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 17.088327
Epoch  100/2000 Cost: 17.088327
Epoch  200/2000 Cost: 17.088327
Epoch  300/2000 Cost: 17.088327
Epoch  400/2000 Cost: 17.088327
Epoch  500/2000 Cost: 17.088327
Epoch  600/2000 Cost: 17.088327
Epoch  700/2000 Cost: 17.088327
Epoch  800/2000 Cost: 17.088327
Epoch  900/2000 Cost: 17.088327
Epoch 1000/2000 Cost: 17.088327
Epoch 1100/2000 Cost: 17.088327
Epoch 1200/2000 Cost: 17.088327
Epoch 1300/2000 Cost: 17.088327
Epoch 1400/2000 Cost: 17.088327
Epoch 1500/2000 Cost: 17.088327
Epoch 1600/2000 Cost: 17.088327
Epoch 1700/2000 Cost: 17.088327
Epoch 1800/2000 Cost: 17.088327
Epoch 1900/2000 Cost: 17.088327
Epoch 2000/2000 Cost: 17.088327
