# NUMPY Tutorial
- 2020.01.28

In [12]:
# Import Package
import numpy as np

In [13]:
array = np.array([1, 2, 3])
print("Size of array :" , array.size) 
print("Type of array :" , array.dtype) 
print("Second element in array :" , array[1]) 

Size of array : 3
Type of array : int32
Second element in array : 2


In [14]:
A = np.arange(5)  # 0 ~ 4
print(A)

[0 1 2 3 4]


In [15]:
B = np.zeros((4,3))  # 4 by 3 zero matrix (numpy array)
print(B)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
C = np.random.randint(0, 10, (3, 3))  # Random number
print(C)

[[0 3 3]
 [1 4 2]
 [7 2 2]]


In [17]:
array1 = np.array([1, 2, 3, 4])
print(array1.shape)  # 1 rank

(4,)


In [18]:
array2 = array1.reshape((2, 2))
print(array2.shape)
print(array2)

(2, 2)
[[1 2]
 [3 4]]


In [19]:
a = np.array([[1,2],[3,4]])
b = np.array([[10,20],[30,40]])

In [20]:
# Matrix Addition
c = a + b
c

array([[11, 22],
       [33, 44]])

In [21]:
# Matrix Subtraction
d = b - a
d

array([[ 9, 18],
       [27, 36]])

In [22]:
# Element - wise Multiplication
e = a * b
e

array([[ 10,  40],
       [ 90, 160]])

In [23]:
# Matrix Multiplication
f = a @ b
# f = np.dot(a,b)
# f = np.matmul(a,b)
f

array([[ 70, 100],
       [150, 220]])

In [24]:
s = np.ones((4,3))
s

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
t = np.full((2,2),10)
t

array([[10, 10],
       [10, 10]])

In [27]:
t = np.full((3,2),10)
s @ t

array([[30., 30.],
       [30., 30.],
       [30., 30.],
       [30., 30.]])

In [28]:
np.arange(0,10)  # 0 ~ 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [30]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
np.arange(0,6).reshape(3,2).sum(axis=0)

array([6, 9])

In [32]:
np.arange(0,6).reshape(3,2).sum(axis=1)

array([1, 5, 9])

In [33]:
a

array([[1, 2],
       [3, 4]])

In [34]:
# Indexing
print(a[0,0])
print(a[1,0])

1
3
